Events for state dump to socket
grafnu/faucet pull request #20
Opened 2019-10-23 16:09 UTC by anurag6

Yet to add L2_LEARN events. Raising PR to get conversation started.

2019-10-23 16:48 UTC, grafnu commented
Should be against events2 branch to avoid confusion with upstream FaucetSDN PR.

2019-10-23 17:32 UTC, grafnu requested changes

2019-10-23 17:32 UTC, grafnu commented on faucet/faucet_event.py
> +        self.conn_handlers = []
new_conn_handlers?

2019-10-23 17:32 UTC, grafnu commented on faucet/faucet_event.py
> +    def _new_conn_handler(self):
_call_new_conn_handlers?

2019-10-23 17:32 UTC, grafnu commented on faucet/valve.py
> +        if self.dp.dyn_running:
simplify code with intermediate variable for reason

2019-10-23 17:32 UTC, grafnu commented on faucet/valves_manager.py
> +        root = ""
initialize to None

2019-10-23 18:03 UTC, anurag6 commented
@grafnu pTAL

2019-10-23 18:07 UTC, grafnu approved these changes

2019-10-24 00:25 UTC, grafnu commented
You should submit this now, and add the other stuff in another PR.  There is no reason they should be lumped together.  Smaller PR == better.

2019-10-24 00:28 UTC, merged